const ADD_INGREDIENT = 'ADD_INGREDIENT'
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
const SET_INGREDIENTS = 'SET_INGREDIENTS'
const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

const PURCHASE_BURGUER_START = 'PURCHASE_BURGUER_START'
const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS'
const PURCHASE_BURGUER_FAILED = 'PURCHASE_BURGUER_FAILED'
const PURCHASE_INIT = 'PURCHASE_INIT'

const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED' 

export { 
  ADD_INGREDIENT, 
  REMOVE_INGREDIENT, 
  SET_INGREDIENTS, 
  FETCH_INGREDIENTS_FAILED,
  PURCHASE_BURGUER_SUCCESS,
  PURCHASE_BURGUER_FAILED,
  PURCHASE_BURGUER_START,
  PURCHASE_INIT,
  FETCH_ORDERS_START,
  FETCH_ORDERS_SUCCESS,
  FETCH_ORDERS_FAILED
}