const ADD_INGREDIENT = 'ADD_INGREDIENT'
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
const SET_INGREDIENTS = 'SET_INGREDIENTS'
const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
const PURCHASE_BURGUER_SUCCESS = 'PURCHASE_BURGUER_SUCCESS'
const PURCHASE_BURGUER_FAILED = 'PURCHASE_BURGUER_FAILED'

export { 
  ADD_INGREDIENT, 
  REMOVE_INGREDIENT, 
  SET_INGREDIENTS, 
  FETCH_INGREDIENTS_FAILED,
  PURCHASE_BURGUER_SUCCESS,
  PURCHASE_BURGUER_FAILED
}